### PR TITLE
fixes dsyer/spring-boot-thin-launcher#67

### PR DESCRIPTION
**Pull request by stefanocke**

### CODE REVIEW

**Comment by dsyer** [comment]
Awesome, thanks! How about a test? I don't know how easy it is, but it doesn't hurt to ask.

**Comment by stefanocke** [comment]
You are right, I will try again.
I was going to use your test resource snapshot/pom.xml. 
But it did not contain any relevant snapshot dependency. Can you give some hint about its purpose?

**Comment by dsyer** [comment]
I think that's an error. I changed the version at some point by mistake. Probably trying to speed up the build. Maybe we need a different test for that as well.

**Comment by dsyer** [comment]
That looks fine, as far as having a test goes. It's going to slow down the build though, so we might have to think of something lower level (more of a unit test than an integration test). I'll merge this though.

**Comment by dsyer** [comment]
Fixed and rebased to 308080

**Comment by dsyer** [comment]
Thanks again. BTW: I forgot to ask you to click though this: https://cla.pivotal.io/sign/spring.

**Comment by pivotal-issuemaster** [comment]
@stefanocke Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=dsyer/spring-boot-thin-launcher&pullRequestId=72)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=dsyer/spring-boot-thin-launcher&pullRequestId=72) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@stefanocke Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=dsyer/spring-boot-thin-launcher&pullRequestId=72)!

**Pull request merged**
