### PR TITLE
unique key name for generated thin.properties

### PR DESCRIPTION
**Pull request by dantran**
for #80

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dantran Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=dsyer/spring-boot-thin-launcher&pullRequestId=81)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=dsyer/spring-boot-thin-launcher&pullRequestId=81) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dantran Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=dsyer/spring-boot-thin-launcher&pullRequestId=81)!

**Comment by dsyer** [comment]
Thanks for the patch. I don't like using just the counter for properties keys, though. I think ideally we need something that identifies each dependency in a human readable (and reproducible) way. And I'd prefer not to change the default from what it is now, just in case anyone is relying on it. To fix this issue we will have to actually detect a duplicate key and generate something unique to prevent a clash only if it is needed.

**Comment by dantran** [comment]
Ah, I thought we agree on the counter properties key.  it makes sense to me to map a Maven GAV coordinate within a file. This way I don't have to deal with duplicate keys

Do understand the need to be backward compatible.

**Pull request closed without merging**
